# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T11:33:15+00:00



import argparse
import json
import os
from typing import *
from typing import Optional

from autogen.mcp.mcp_proxy import MCPProxy
from autogen.mcp.mcp_proxy.security import APIKeyHeader, BaseSecurity

app = MCPProxy(
    description='VersionEye is a cross-platform search engine for free/libre/open source software libraries.',
    title='API V1',
    version='v1',
    servers=[
        {
            'url': 'https://{defaultHost}',
            'variables': {'defaultHost': {'default': 'www.versioneye.com'}},
        },
        {
            'url': 'http://{defaultHost}',
            'variables': {'defaultHost': {'default': 'localhost:8080'}},
        },
    ],
)


@app.get(
    '/api/v1/scans',
    tags=['scan_data_handling'],
    security=[
        APIKeyHeader(name="apiKey"),
    ],
)
def get_api_v1_scans(name: Optional[str] = None, per_page: Optional[str] = None):
    """
    Retrieves all scans
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/api/v1/scans/{id}',
    tags=['scan_data_handling'],
    security=[
        APIKeyHeader(name="apiKey"),
    ],
)
def get_api_v1_scans__id(id: str):
    """
    Retrieves a project scan result
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/api/v1/scans/{id}/files/{file_id}',
    tags=['file_dependency_info'],
    security=[
        APIKeyHeader(name="apiKey"),
    ],
)
def get_api_v1_scans__id_files__file_id(
    id: str, file_id: str = ..., per_page: Optional[str] = None
):
    """
    Retrieves a file object, containing information about dependencies in the file
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="MCP Server")
    parser.add_argument(
        "transport",
        choices=["stdio", "sse", "streamable-http"],
        help="Transport mode (stdio, sse or streamable-http)",
    )
    args = parser.parse_args()

    if "CONFIG_PATH" in os.environ:
        config_path = os.environ["CONFIG_PATH"]
        app.load_configuration(config_path)

    if "CONFIG" in os.environ:
        config = os.environ["CONFIG"]
        app.load_configuration_from_string(config)

    if "SECURITY" in os.environ:
        security_params = BaseSecurity.parse_security_parameters_from_env(
            os.environ,
        )

        app.set_security_params(security_params)

    mcp_settings = json.loads(os.environ.get("MCP_SETTINGS", "{}"))

    app.get_mcp(**mcp_settings).run(transport=args.transport)
